apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: java
        image: bharath0812/tomcat:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: httpdservice
spec:
 type: NodePort
 selector:
   app: webapp
 ports:
   - port: 8082
     targetPort: 8080
     nodePort: 32140
     protocol: TCP
